
services:

# Frontend Service (React + Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    container_name: frontend
    depends_on:
      - api-gateway
    ports:
      - "3000:5173"
    networks:
      - spring-net  

#API Gateway
  api-gateway:
    build: ./backend/api-gateway
    container_name: api-gateway
    depends_on:
      - eureka-server
      - security-service
      - member-service
      - expedition-service
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
    networks:
      - spring-net

#Security Service
  security-service:
    build: ./backend/security-service
    container_name: security-service
    depends_on:
      - postgres
    ports:
      - "8084:8080"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/securityDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
    networks:
      - spring-net

#Member Service
  member-service:
    build: ./backend/member-service
    container_name: member-service
    depends_on:
      - postgres
      - eureka-server
      - payment-service
    ports:
      - "8081:8080"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/memberDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
    networks:
      - spring-net

#Expedition Service
  expedition-service:
    build: ./backend/expedition-service
    container_name: expedition-service
    depends_on:
      - postgres
      - eureka-server
      - payment-service
    ports:
      - "8082:8080"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/expeditionDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
    networks:
      - spring-net

#Payment Service
  payment-service:
    build: ./backend/payment-service
    container_name: payment-service
    depends_on:
      - postgres
    ports:
      - "8083:8080"
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/paymentDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
    networks:
      - spring-net

#Eureka Server
  eureka-server:
    build: ./backend/eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
    networks:
      - spring-net

#pgAdmin (web UI for PostgreSQL)
  pgadmin:
    image: dpage/pgadmin4:8.12
    container_name: pgadmin
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - spring-net

#PostgreSQL
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: main
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    networks:
      - spring-net

networks:
  spring-net:
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data:
